#!/usr/bin/env bash
# Download this gist into file "~/.xd_swi"
#    curl -Ls https://gist.github.com/andkirby/8db337ea6495951e6f952005ce7c170b/raw/.xd_swi -o ~/.xd_swi
# And run:
#    ~/.xd_swi

curl -Ls https://gist.github.com/andkirby/8db337ea6495951e6f952005ce7c170b/raw/.xd_swi -o ~/.xd_swi
chmod u+x ~/.xd_swi

echo >> ~/.bashrc
echo '# autogenerated. Switch xdebug status' >> ~/.bashrc
echo 'alias xd_swi=~/.xd_swi' >> ~/.bashrc

echo 'XDebug switcher has been installed. (file ~/.xd_swi)'
echo '  Alias: xd_swi'
